#!/usr/bin/env python3
"""Build and validate the repository-wide skill index."""

from __future__ import annotations

import argparse
import difflib
import json
import os
from dataclasses import dataclass
from pathlib import Path
import re
import stat
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
AGENTS_PATH = ROOT / "AGENTS.md"
SKILL_GLOB = "plugins/*/skills/*/SKILL.md"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
FIELD_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
THIRD_PERSON_RE = re.compile(r"^(?:Does|Has|Is|[A-Z][A-Za-z'-]*s)\b")
CONTROL_RE = re.compile(r"[\x00-\x1f\x7f]")

AGENTS_PREAMBLE = """# selfos-skills — Agent Operating Guide

If the task matches a skill in the table below, read that skill's `SKILL.md` in full and follow it; resolve relative paths in a skill from that skill's folder.
Rows marked **Explicit invocation only** run solely at the user's explicit request — a topical match is not an invitation to load them.
Otherwise (maintenance, adding a skill, reviewing changes) work normally — the table is a capability index, not a requirement.
This repository is public: use invented examples only; never commit real personal data, credentials, or local agent/tool state.

<!-- Generated by scripts/build_index.py; do not edit by hand. -->
"""

EXPLICIT_ONLY_NOTE = (
    " **Explicit invocation only:** load this skill solely when the user names it or asks to"
    " run it — never because a request merely matches this description."
)


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    path: Path
    explicit_only: bool = False


def display_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def parse_scalar(raw: str, path: Path, line_number: int) -> tuple[str | None, list[str]]:
    """Parse the small, single-line scalar subset used by skill frontmatter."""
    def result(parsed: str) -> tuple[str | None, list[str]]:
        if CONTROL_RE.search(parsed):
            return None, [
                f"{display_path(path)}:{line_number}: frontmatter values must not contain control characters"
            ]
        return parsed, []

    value = raw.strip()
    if not value:
        return None, [f"{display_path(path)}:{line_number}: frontmatter value must not be empty"]

    if value.startswith('"'):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            return None, [
                f"{display_path(path)}:{line_number}: invalid double-quoted frontmatter value: {exc.msg}"
            ]
        if not isinstance(parsed, str):
            return None, [f"{display_path(path)}:{line_number}: frontmatter value must be text"]
        return result(parsed)

    if value.startswith("'"):
        if len(value) < 2 or not value.endswith("'"):
            return None, [f"{display_path(path)}:{line_number}: unterminated single-quoted frontmatter value"]
        inner = value[1:-1]
        parsed_characters: list[str] = []
        index = 0
        while index < len(inner):
            if inner[index] != "'":
                parsed_characters.append(inner[index])
                index += 1
                continue
            if index + 1 >= len(inner) or inner[index + 1] != "'":
                return None, [
                    f"{display_path(path)}:{line_number}: apostrophes in single-quoted frontmatter must be doubled"
                ]
            parsed_characters.append("'")
            index += 2
        return result("".join(parsed_characters))

    if value[0] in ">|":
        return None, [
            f"{display_path(path)}:{line_number}: use a single-line name or description value"
        ]

    return result(value)


def parse_skill(path: Path) -> tuple[Skill | None, list[str]]:
    errors: list[str] = []
    relative = display_path(path)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError) as exc:
        return None, [f"{relative}: cannot read UTF-8 skill file: {exc}"]

    if not lines or lines[0].strip() != "---":
        return None, [f"{relative}:1: SKILL.md must start with a frontmatter delimiter (---)"]

    try:
        closing_index = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration:
        return None, [f"{relative}: frontmatter is missing its closing delimiter (---)"]

    fields: dict[str, tuple[str | None, int]] = {}
    for index, line in enumerate(lines[1:closing_index], start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[:1].isspace():
            errors.append(f"{relative}:{index}: frontmatter fields must be single-line key: value pairs")
            continue

        key, separator, raw_value = line.partition(":")
        key = key.strip()
        if not separator or not FIELD_RE.fullmatch(key):
            errors.append(f"{relative}:{index}: malformed frontmatter field; expected key: value")
            continue
        if key in fields:
            errors.append(f"{relative}:{index}: duplicate frontmatter field {key!r}")
            continue

        value, scalar_errors = parse_scalar(raw_value, path, index)
        errors.extend(scalar_errors)
        fields[key] = (value, index)

    for required in ("name", "description"):
        if required not in fields:
            errors.append(f"{relative}: frontmatter is missing required field {required!r}")

    if "name" not in fields or "description" not in fields:
        return None, errors

    name, name_line = fields["name"]
    description, description_line = fields["description"]
    if name is None or description is None:
        return None, errors

    if not NAME_RE.fullmatch(name):
        errors.append(
            f"{relative}:{name_line}: name must be kebab-case (lowercase letters, digits, and single hyphens)"
        )
    if name != path.parent.name:
        errors.append(
            f"{relative}:{name_line}: name {name!r} must match skill folder {path.parent.name!r}"
        )

    if len(description) > 1024:
        errors.append(
            f"{relative}:{description_line}: description is {len(description)} characters; maximum is 1024"
        )

    summary, trigger_separator, trigger = description.partition(". Use when ")
    if not trigger_separator or not summary or not trigger.strip():
        errors.append(
            f"{relative}:{description_line}: description must be third-person summary text followed by '. Use when …' triggers"
        )
    elif not THIRD_PERSON_RE.match(summary):
        errors.append(
            f"{relative}:{description_line}: description summary must begin in third-person form (for example, 'Reviews …')"
        )

    invocation_raw = fields.get("disable-model-invocation", (None, 0))[0]
    explicit_only = isinstance(invocation_raw, str) and invocation_raw.strip().lower() == "true"

    return Skill(name=name, description=description, path=path, explicit_only=explicit_only), errors


def load_skills() -> tuple[list[Skill], list[str]]:
    paths = sorted(ROOT.glob(SKILL_GLOB))
    if not paths:
        return [], [f"no skills found at {SKILL_GLOB}"]

    skills: list[Skill] = []
    errors: list[str] = []
    for path in paths:
        skill, skill_errors = parse_skill(path)
        errors.extend(skill_errors)
        if skill is not None:
            skills.append(skill)

    seen: dict[str, Path] = {}
    for skill in sorted(skills, key=lambda item: (item.name, display_path(item.path))):
        previous = seen.get(skill.name)
        if previous is not None:
            errors.append(
                f"{display_path(skill.path)}: duplicate skill name {skill.name!r}; "
                f"already used by {display_path(previous)}"
            )
        else:
            seen[skill.name] = skill.path

    return sorted(skills, key=lambda item: (item.name, display_path(item.path))), errors


def escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|")


def render_agents(skills: list[Skill]) -> str:
    rows = [
        "| Name | When to use | Path |",
        "| --- | --- | --- |",
    ]
    for skill in skills:
        path = display_path(skill.path)
        description = skill.description
        if skill.explicit_only:
            description += EXPLICIT_ONLY_NOTE
        rows.append(
            f"| `{skill.name}` | {escape_table_cell(description)} | [{path}]({path}) |"
        )
    return AGENTS_PREAMBLE + "\n".join(rows) + "\n"


def write_atomically(path: Path, content: str) -> None:
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.chmod(temporary_path, mode)
        os.replace(temporary_path, path)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def check_agents(expected: str) -> int:
    try:
        actual = AGENTS_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        print("ERROR: AGENTS.md is missing; run python scripts/build_index.py", file=sys.stderr)
        return 1
    except (OSError, UnicodeError) as exc:
        print(f"ERROR: cannot read AGENTS.md: {exc}", file=sys.stderr)
        return 1

    if actual == expected:
        return 0

    print("ERROR: AGENTS.md is stale; run python scripts/build_index.py", file=sys.stderr)
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile="AGENTS.md (current)",
        tofile="AGENTS.md (generated)",
        lineterm="",
    )
    for line in diff:
        print(line, file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate skill metadata and fail if AGENTS.md is stale",
    )
    args = parser.parse_args()

    skills, errors = load_skills()
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    expected = render_agents(skills)
    if args.check:
        if check_agents(expected) != 0:
            return 1
        print(f"OK: validated {len(skills)} skills; AGENTS.md is up to date.")
        return 0

    try:
        current = AGENTS_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current == expected:
        print(f"AGENTS.md is already up to date ({len(skills)} skills).")
        return 0

    write_atomically(AGENTS_PATH, expected)
    print(f"Wrote AGENTS.md with {len(skills)} skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
