#!/usr/bin/env python3
"""Build the generated fallback catalog in AGENTS.md from canonical skills/."""

from __future__ import annotations

import argparse
import difflib
import os
from pathlib import Path
import stat
import sys
import tempfile

from skill_catalog import ROOT, discover_skills, display_path

AGENTS_PATH = ROOT / "AGENTS.md"
PREAMBLE = """# selfos-skills — Portable Agent Skills Catalog

The installable source of truth is `skills/<name>/`, following the open Agent Skills format. Installers and native plugin systems discover those folders directly; this file is only a generated catalog and a fallback for agents that can read repository instructions but do not yet support skills.

When working inside this repository, read a matching skill's `SKILL.md` in full and resolve every relative path from that skill folder. Rows marked **explicit only** must not auto-activate from a topical match. This repository is public: use invented examples only and never commit personal data, credentials, private paths, or local agent state.

<!-- Generated by scripts/build_index.py; do not edit by hand. -->
"""


def escape(value: str) -> str:
    return value.replace("|", "\\|")


def render() -> tuple[str | None, list[str]]:
    skills, errors = discover_skills()
    if errors:
        return None, errors
    rows = [
        "| Name | When to use | Invocation | Bundled references | Path |",
        "| --- | --- | --- | --- | --- |",
    ]
    for skill in skills:
        invocation = "**explicit only**" if skill.explicit_only else "automatic or explicit"
        bundled = ", ".join(f"`{name}`" for name in skill.vendored_skills) or "—"
        path = display_path(skill.path)
        rows.append(
            f"| `{skill.name}` | {escape(skill.description)} | {invocation} | {bundled} | [{path}]({path}) |"
        )
    return PREAMBLE + "\n".join(rows) + "\n", []


def write_atomically(path: Path, content: str) -> None:
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if AGENTS.md is stale")
    args = parser.parse_args()
    expected, errors = render()
    if errors or expected is None:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    try:
        actual = AGENTS_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        actual = ""
    except (OSError, UnicodeError) as exc:
        print(f"ERROR: cannot read AGENTS.md: {exc}", file=sys.stderr)
        return 1

    if actual == expected:
        print("AGENTS.md is up to date.")
        return 0
    if args.check:
        print("ERROR: AGENTS.md is stale; run python scripts/build_index.py", file=sys.stderr)
        for line in difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile="AGENTS.md (current)",
            tofile="AGENTS.md (generated)",
            lineterm="",
        ):
            print(line, file=sys.stderr)
        return 1
    write_atomically(AGENTS_PATH, expected)
    print("Wrote AGENTS.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
